import 'package:volcminer/presentation/localization/app_language.dart';

class AppStrings {
  AppStrings._();

  static final Map<String, String> _en = {
    'app.title.dashboard': 'VolcMiner Dashboard',
    'app.title.scan': 'Scan',
    'app.title.results': 'Scan Results',
    'app.title.settings': 'Settings',
    'app.scan.progress': 'Scanning {current}/{total}',
    'app.scan.paused': 'Scan paused at {current}/{total}',
    'app.scan.finalizing': 'Finalizing scan results...',
    'app.scanner.open': 'Open Scanner',
    'app.nav.dashboard': 'Dashboard',
    'app.nav.scan': 'Scan',
    'app.nav.results': 'Results',
    'app.nav.settings': 'Settings',
    'overview.onlineMiners': 'Online Miners',
    'overview.unresponsiveMiners': 'Unresponsive Miners',
    'overview.offlineMiners': 'Offline Miners',
    'overview.allOnlineTitle': 'All Online Miners',
    'overview.allUnresponsiveTitle': 'All Unresponsive Miners',
    'overview.allOfflineTitle': 'All Offline Miners',
    'overview.emptyCategory': 'No miners in this category.',
    'overview.scope': 'IP Block: {scope}',
    'overview.totalHashrate': 'Total Hashrate',
    'overview.onlineRate': 'Online Rate',
    'overview.scanSchedule': 'Scan Schedule',
    'overview.dataAsOf': 'Current data as of {time}',
    'overview.nextScanAt': 'Next scan: {time}',
    'overview.nextScanIn': 'Next scan in {duration}',
    'overview.autoRefreshOff': 'Auto refresh is off',
    'overview.waitingFirstAutoScan': 'Waiting for the first auto refresh',
    'overview.scanOverdue': 'Scheduled scan is overdue',
    'overview.currentHashrate': 'Current Hashrate',
    'overview.averageHashrate': 'Average Hashrate',
    'overview.averageWindow1h': '1H',
    'overview.averageWindow12h': '12H',
    'overview.hourlyHashrateChart': 'Hourly Average Hashrate',
    'overview.chartEmpty': 'Not enough scan history yet.',
    'overview.unstableScopes': 'IP Blocks With Repeated Dropouts',
    'overview.unstableScopesEmpty': 'No repeated dropout IP blocks found yet.',
    'app.scan.action.scan': 'Scan',
    'app.scan.action.scanning': 'Scanning...',
    'app.scan.action.pause': 'Pause',
    'app.scan.action.resume': 'Resume',
    'app.scan.action.cancel': 'Cancel Scan',
    'app.scan.action.cancelling': 'Cancelling...',
    'common.clearInput': 'Clear input',
    'settings.language': 'Language',
    'settings.language.en': 'English',
    'settings.language.zh': 'Chinese',
    'settings.fontScale': 'Font Scale',
    'settings.autoRefresh': 'Auto Refresh',
    'settings.showOffline': 'Show Offline Miners',
    'settings.collectLogs': 'Collect Logs',
    'settings.refreshInterval': 'Auto refresh interval (sec)',
    'settings.scanConcurrency': 'Scan Concurrency',
    'settings.scanConcurrencyWarningTitle': 'Use concurrency 60?',
    'settings.scanConcurrencyWarningBody':
        'Concurrency 60 can significantly increase pressure on this device, Wi-Fi, router, and miner web service.',
    'settings.scanConcurrencyWarningHint':
        'Use it only when the local network is stable and device performance is strong.',
    'dashboard.scanType': 'Scan Type',
    'dashboard.scanType.full': 'Full Scan',
    'dashboard.scanType.known': 'Known Scan',
    'dashboard.scanType.fullDesc':
        'Scan the full selected IP range, for example 1-255.',
    'dashboard.scanType.knownDesc':
        'Only scan known miner IPs already recorded for this IP block.',
    'dashboard.minerAuth': 'Miner Auth',
    'dashboard.addScanView': 'Add Scan View',
    'dashboard.searchIpBlock': 'Search IP Block',
    'dashboard.searchIpBlockHint': 'Example: 100.16',
    'dashboard.minerUsername': 'Miner Username',
    'dashboard.minerPassword': 'Miner Password',
    'dashboard.baseIpBlock': 'Base IP Block',
    'dashboard.ipBlockOptional': 'IP Block (optional)',
    'dashboard.baseIpBlockHint': 'Example: 172.100',
    'dashboard.ipBlockHint': 'Example: 172.100.1',
    'dashboard.batchAdd': 'Batch Add Views',
    'dashboard.batchAddTitle': 'Batch add views',
    'dashboard.batchAddSubtitle':
        'Add IP blocks in order, for example 172.100.1 to 172.100.20.',
    'dashboard.batchStart': 'Batch Start',
    'dashboard.batchEnd': 'Batch End',
    'dashboard.startIp': 'Start IP / Host (optional)',
    'dashboard.endIp': 'End IP / Host (optional)',
    'dashboard.startIpHint': '1 or 172.100.1.1',
    'dashboard.endIpHint': '255 or 172.100.1.255',
    'dashboard.addView': 'Add View',
    'dashboard.selectionMode': 'Selection Mode:',
    'dashboard.selectionMode.single': 'Single',
    'dashboard.selectionMode.multi': 'Multi',
    'dashboard.selectionMode.selectAll': 'Select All',
    'dashboard.error.invalidIpBlock': 'Invalid IP Block format',
    'dashboard.error.invalidRange':
        'Invalid start/end IP format. You can use a full IP or a host suffix with IP Block.',
    'dashboard.error.startGreaterThanEnd':
        'Start IP must be less than or equal to End IP.',
    'dashboard.error.batchBase':
        'Batch add requires a base IP Block like 172.100',
    'dashboard.error.batchBaseInvalid': 'Invalid base IP Block',
    'dashboard.error.batchRangeInvalid': 'Invalid batch range',
    'dashboard.defaultViewName': 'IP Block',
    'results.empty':
        'No scan records yet. Start a scan from Dashboard first.',
    'results.searchLabel': 'Search IP Block',
    'results.searchHint': 'Example: 100.1 or 101.16',
    'results.lastScan': 'Last Scan: {time}',
    'results.ipBlock': 'IP Block: {scope}',
    'results.onlineMiners': 'Online Miners: {count}',
    'results.unresponsiveMiners': 'Unresponsive: {count}',
    'results.offlineMiners': 'Offline: {count}',
    'results.retiredMiners': 'Retired: {count}',
    'results.trackedMiners': 'Tracked Miners: {count}',
    'results.issueCount': 'Issues: {count}',
    'segment.title': '{scope} Details',
    'segment.lastScan': 'Last Scan: {time}',
    'segment.onlineCount': 'Online Count: {count}',
    'segment.filter.all': 'All',
    'segment.filter.online': 'Online',
    'segment.filter.unresponsive': 'Unresponsive',
    'segment.filter.offline': 'Offline',
    'segment.filter.retired': 'Retired',
    'segment.selected': 'Selected: {count}',
    'segment.selectAll': 'Select All',
    'segment.cancelSelect': 'Cancel Selection',
    'segment.batchLedOn': 'Batch LED On',
    'segment.batchLedOnBusy': 'Turning on...',
    'segment.batchLedOff': 'Batch LED Off',
    'segment.batchLedOffBusy': 'Turning off...',
    'segment.poolConfig': 'Pool Config ({count})',
    'segment.batchClear': 'Batch Clear Refine',
    'segment.batchClearBusy': 'Clearing...',
    'segment.batchReboot': 'Batch Reboot Miners',
    'segment.batchRebootBusy': 'Rebooting...',
    'segment.longPressHint':
        'Long press a miner record to enter multi-select mode.',
    'segment.ledOnTag': 'LED on',
    'segment.issueReason': 'Issue: {reason}',
    'segment.issueSolution': 'Suggestion: {solution}',
    'segment.issueSecondary': 'Secondary symptom: {reason}',
    'segment.deleteMiner': 'Delete Miner',
    'segment.deleteMinerMessage':
        'Delete off-shelf miner record {ip}?',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'segment.confirmLedOnTitle': 'Confirm batch LED on',
    'segment.confirmLedOnMessage':
        'Turn on the indicator light for {count} selected miners?',
    'segment.confirmLedOffTitle': 'Confirm batch LED off',
    'segment.confirmLedOffMessage':
        'Turn off the indicator light for {count} selected miners?',
    'segment.confirmClearTitle': 'Confirm batch clear refine',
    'segment.confirmClearMessage':
        'Clear refine for {count} selected miners?',
    'segment.confirmRebootTitle': 'Confirm batch reboot',
    'segment.confirmRebootMessage':
        'Reboot {count} selected miners?',
    'miner.status': 'Status: {status}',
    'miner.hashrate5s': 'Hashrate 5s: {value}',
    'miner.hashrateAvg': 'Hashrate avg: {value}',
    'miner.ambientTemp': 'Ambient temp: {value}',
    'miner.power': 'Power: {value}',
    'miner.fans': 'Fans: {value}',
    'miner.runningMode': 'Running mode: {value}',
    'miner.updated': 'Updated: {time}',
    'miner.indicatorSwitch': 'Indicator switch',
    'miner.sendingCommand': 'Sending command...',
    'miner.indicatorHint': 'Uses diagnostics backend to control the miner LED.',
    'miner.clearRefine': 'Clear Refine',
    'miner.clearRefineMessage': 'Clear refine for {ip}?',
    'miner.rebootMiner': 'Reboot Miner',
    'miner.rebootMinerMessage': 'Reboot {ip} now?',
    'miner.refresh': 'Refresh',
    'miner.refreshing': 'Refreshing miner...',
    'miner.refreshDone': 'Miner refreshed: {ip}',
    'miner.refreshFailed': 'Miner refresh failed: {error}',
    'miner.poolConfig': 'Pool Config',
    'miner.kernelLog': 'Kernel Log',
    'miner.kernelLogLoading': 'Loading full kernel log...',
    'miner.kernelLogFailed': 'Load failed',
    'miner.kernelLogCollapsed': 'Expand to load the full kernel log.',
    'miner.kernelLogReady':
        'Full log loaded. Drag the scrollbars to view it.',
    'miner.kernelLogPlaceholder': 'Expand to load the full work log.',
    'miner.kernelLogError': 'Kernel log load failed: {error}',
    'miner.issueCardTitle': 'Zero Hash Diagnosis',
    'miner.issueReason': 'Reason: {reason}',
    'miner.issueSolution': 'Suggestion: {solution}',
    'miner.issueCode': 'Code: {code}',
    'miner.issueSecondary': 'Secondary symptom: {reason}',
    'status.online': 'Online',
    'status.offline': 'Offline',
    'pool.applyTitle': 'Apply Pool Config',
    'pool.title': 'Pool Config',
    'pool.targetSingle': 'Target: {ip}',
    'pool.targetMulti': 'Targets: {count} miners',
    'pool.singleHint':
        'The pool fields below are loaded from the current miner first.',
    'pool.multiHint':
        'Edit the pool slots below, then apply them to the selected miners.',
    'pool.slots': 'Pool Slots',
    'pool.slotTitle': 'Pool Slot {slot}',
    'pool.url': 'Pool URL',
    'pool.workerCode': 'Worker Code',
    'pool.password': 'Password',
    'pool.applying': 'Applying...',
    'pool.applySingle': 'Apply to Miner',
    'pool.applyMulti': 'Apply to Selected Miners',
    'pool.fillOneSlot': 'Please fill at least one pool slot first.',
    'pool.confirmSwitch': 'Confirm Pool Switch',
    'pool.confirmSwitchSingle':
        'Apply the current pool configuration to {ip}?',
    'pool.confirmSwitchMulti':
        'Apply the current pool configuration to {count} selected miners?',
    'view.ipBlock': 'IP Block: {scope}',
    'view.range': 'Range: {start} - {end}',
    'view.deleteTitle': 'Delete View',
    'view.deleteMessage': 'Delete view {scope}?',
    'controller.scanView.loadFailed': 'Failed to load scan views: {error}',
    'controller.scanView.duplicate': 'This view already exists.',
    'controller.scan.selectOne': 'Please select at least one scan view.',
    'controller.scan.knownEmpty':
        'Selected IP blocks do not have known miners yet.',
    'controller.scan.invalidRange':
        'Selected views do not contain valid IP ranges.',
    'controller.scan.poolCheckFailed': 'Pool check failed: {error}',
    'controller.scan.scanFailed': 'Scan failed: {error}',
  };

  static final Map<String, String> _zh = {
    'app.title.dashboard': '火山矿机面板',
    'app.title.scan': '扫描',
    'app.title.results': '扫描结果',
    'app.title.settings': '设置',
    'app.scan.progress': '扫描中 {current}/{total}',
    'app.scan.paused': '扫描已暂停 {current}/{total}',
    'app.scan.finalizing': '正在整理扫描结果...',
    'app.scanner.open': '打开扫码',
    'app.nav.dashboard': '面板',
    'app.nav.scan': '扫描',
    'app.nav.results': '结果',
    'app.nav.settings': '设置',
    'overview.onlineMiners': '在线矿机',
    'overview.unresponsiveMiners': '未响应矿机',
    'overview.offlineMiners': '离线矿机',
    'overview.allOnlineTitle': '全部在线矿机',
    'overview.allUnresponsiveTitle': '全部未响应矿机',
    'overview.allOfflineTitle': '全部离线矿机',
    'overview.emptyCategory': '当前分类下没有矿机。',
    'overview.scope': 'IP 段：{scope}',
    'overview.totalHashrate': '整体算力',
    'overview.onlineRate': '在线率',
    'overview.scanSchedule': '扫描计划',
    'overview.dataAsOf': '当前信息截至 {time}',
    'overview.nextScanAt': '下次扫描时间：{time}',
    'overview.nextScanIn': '距离下次扫描还有 {duration}',
    'overview.autoRefreshOff': '自动刷新未开启',
    'overview.waitingFirstAutoScan': '等待首次自动刷新',
    'overview.scanOverdue': '已到计划时间，等待执行',
    'overview.currentHashrate': '当前整体算力',
    'overview.averageHashrate': '平均算力',
    'overview.averageWindow1h': '1小时',
    'overview.averageWindow12h': '12小时',
    'overview.hourlyHashrateChart': '小时平均算力折线图',
    'overview.chartEmpty': '当前历史扫描数据不足。',
    'overview.unstableScopes': '存在多次掉线问题的 IP 段',
    'overview.unstableScopesEmpty': '暂时没有发现多次掉线的 IP 段。',
    'app.scan.action.scan': '开始扫描',
    'app.scan.action.scanning': '扫描中...',
    'app.scan.action.pause': '暂停',
    'app.scan.action.resume': '继续扫描',
    'app.scan.action.cancel': '取消扫描',
    'app.scan.action.cancelling': '正在取消...',
    'common.clearInput': '清空输入',
    'settings.language': '语言',
    'settings.language.en': 'English',
    'settings.language.zh': '中文',
    'settings.fontScale': '字体大小',
    'settings.autoRefresh': '自动刷新',
    'settings.showOffline': '显示离线矿机',
    'settings.collectLogs': '采集日志',
    'settings.refreshInterval': '自动刷新间隔（秒）',
    'settings.scanConcurrency': '扫描并发数',
    'settings.scanConcurrencyWarningTitle': '确认使用并发 60',
    'settings.scanConcurrencyWarningBody':
        '并发 60 会明显增加本机、Wi‑Fi、路由器和矿机 Web 服务的负载。',
    'settings.scanConcurrencyWarningHint':
        '仅建议在局域网稳定且设备性能足够时使用。',
    'dashboard.scanType': '扫描方式',
    'dashboard.scanType.full': '全段扫描',
    'dashboard.scanType.known': '已知扫描',
    'dashboard.scanType.fullDesc':
        '扫描所选 IP 范围内的完整地址，例如 1-255。',
    'dashboard.scanType.knownDesc':
        '只扫描结果页中当前 IP 段已经记录过的矿机 IP。',
    'dashboard.minerAuth': '矿机认证',
    'dashboard.addScanView': '添加视图',
    'dashboard.searchIpBlock': '搜索 IP 段',
    'dashboard.searchIpBlockHint': '例如 100.16',
    'dashboard.minerUsername': '矿机用户名',
    'dashboard.minerPassword': '矿机密码',
    'dashboard.baseIpBlock': '基础 IP 段',
    'dashboard.ipBlockOptional': 'IP 段（可选）',
    'dashboard.baseIpBlockHint': '例如 172.100',
    'dashboard.ipBlockHint': '例如 172.100.1',
    'dashboard.batchAdd': '批量添加视图',
    'dashboard.batchAddTitle': '批量添加视图',
    'dashboard.batchAddSubtitle':
        '按范围逐个添加 IP 段，例如 172.100.1 到 172.100.20。',
    'dashboard.batchStart': '批量起始',
    'dashboard.batchEnd': '批量结束',
    'dashboard.startIp': '起始 IP / Host（可选）',
    'dashboard.endIp': '结束 IP / Host（可选）',
    'dashboard.startIpHint': '1 或 172.100.1.1',
    'dashboard.endIpHint': '255 或 172.100.1.255',
    'dashboard.addView': '添加视图',
    'dashboard.selectionMode': '选择模式：',
    'dashboard.selectionMode.single': '单选',
    'dashboard.selectionMode.multi': '多选',
    'dashboard.selectionMode.selectAll': '全选',
    'dashboard.error.invalidIpBlock': 'IP 段格式不正确',
    'dashboard.error.invalidRange':
        '起始或结束 IP 格式不正确。可以输入完整 IP，或在 IP 段后只输入主机尾段。',
    'dashboard.error.startGreaterThanEnd': '起始 IP 不能大于结束 IP。',
    'dashboard.error.batchBase': '批量添加需要输入类似 172.100 的基础 IP 段',
    'dashboard.error.batchBaseInvalid': '基础 IP 段无效',
    'dashboard.error.batchRangeInvalid': '批量范围无效',
    'dashboard.defaultViewName': 'IP 段',
    'results.empty': '还没有扫描记录，请先在 Dashboard 发起扫描。',
    'results.searchLabel': '搜索 IP 段',
    'results.searchHint': '例如 100.1 或 101.16',
    'results.lastScan': '上次扫描：{time}',
    'results.ipBlock': 'IP 段：{scope}',
    'results.onlineMiners': '在线矿机：{count}',
    'results.unresponsiveMiners': '未响应：{count}',
    'results.offlineMiners': '离线：{count}',
    'results.retiredMiners': '下架：{count}',
    'results.trackedMiners': '记录矿机：{count}',
    'results.issueCount': '异常：{count}',
    'segment.title': '{scope} 搜索详情',
    'segment.lastScan': '上次扫描：{time}',
    'segment.onlineCount': '在线数量：{count}',
    'segment.filter.all': '全部',
    'segment.filter.online': '在线',
    'segment.filter.unresponsive': '未响应',
    'segment.filter.offline': '离线',
    'segment.filter.retired': '下架',
    'segment.selected': '已选择：{count}',
    'segment.selectAll': '全选',
    'segment.cancelSelect': '取消选择',
    'segment.batchLedOn': '批量开灯',
    'segment.batchLedOnBusy': '开灯中...',
    'segment.batchLedOff': '批量关灯',
    'segment.batchLedOffBusy': '关灯中...',
    'segment.poolConfig': '矿池配置（{count}）',
    'segment.batchClear': '批量清除自适应',
    'segment.batchClearBusy': '清除中...',
    'segment.batchReboot': '批量重启矿机',
    'segment.batchRebootBusy': '重启中...',
    'segment.longPressHint': '长按单个矿机记录可进入批量选择模式。',
    'segment.ledOnTag': '已打开指示灯',
    'segment.issueReason': '原因：{reason}',
    'segment.issueSolution': '建议：{solution}',
    'segment.issueSecondary': '次级症状：{reason}',
    'segment.deleteMiner': '删除矿机',
    'segment.deleteMinerMessage': '删除下架矿机记录 {ip}？',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.confirm': '确认',
    'segment.confirmLedOnTitle': '确认批量打开指示灯',
    'segment.confirmLedOnMessage': '本次将打开 {count} 台矿机的指示灯，是否继续？',
    'segment.confirmLedOffTitle': '确认批量关闭指示灯',
    'segment.confirmLedOffMessage': '本次将关闭 {count} 台矿机的指示灯，是否继续？',
    'segment.confirmClearTitle': '确认批量清除自适应',
    'segment.confirmClearMessage': '本次将清除 {count} 台矿机的自适应，是否继续？',
    'segment.confirmRebootTitle': '确认批量重启矿机',
    'segment.confirmRebootMessage': '本次将重启 {count} 台矿机，是否继续？',
    'miner.status': '状态：{status}',
    'miner.hashrate5s': '5 秒算力：{value}',
    'miner.hashrateAvg': '平均算力：{value}',
    'miner.ambientTemp': '环境温度：{value}',
    'miner.power': '功耗：{value}',
    'miner.fans': '风扇：{value}',
    'miner.runningMode': '运行模式：{value}',
    'miner.updated': '更新时间：{time}',
    'miner.indicatorSwitch': '指示灯开关',
    'miner.sendingCommand': '正在发送指令...',
    'miner.indicatorHint': '通过诊断后台控制矿机指示灯。',
    'miner.clearRefine': '清除自适应',
    'miner.clearRefineMessage': '确认清除 {ip} 的自适应吗？',
    'miner.rebootMiner': '重启矿机',
    'miner.rebootMinerMessage': '确认现在重启 {ip} 吗？',
    'miner.refresh': '刷新',
    'miner.refreshing': '正在刷新矿机...',
    'miner.refreshDone': '矿机已刷新：{ip}',
    'miner.refreshFailed': '矿机刷新失败：{error}',
    'miner.poolConfig': '矿池配置',
    'miner.kernelLog': '工作日志',
    'miner.kernelLogLoading': '正在读取完整 kernel log...',
    'miner.kernelLogFailed': '读取失败',
    'miner.kernelLogCollapsed': '展开后单独读取完整日志。',
    'miner.kernelLogReady': '完整日志已加载，可拖动滚动条查看。',
    'miner.kernelLogPlaceholder': '展开后单独查找完整工作日志。',
    'miner.kernelLogError': '工作日志读取失败：{error}',
    'miner.issueCardTitle': '零算力诊断',
    'miner.issueReason': '原因：{reason}',
    'miner.issueSolution': '建议：{solution}',
    'miner.issueCode': '错误码：{code}',
    'miner.issueSecondary': '次级症状：{reason}',
    'status.online': '在线',
    'status.offline': '离线',
    'pool.applyTitle': '应用矿池配置',
    'pool.title': '矿池配置',
    'pool.targetSingle': '目标：{ip}',
    'pool.targetMulti': '目标：{count} 台矿机',
    'pool.singleHint': '下面的矿池输入框会先加载当前矿机的配置。',
    'pool.multiHint': '修改下面的矿池槽位后，再批量下发到所选矿机。',
    'pool.slots': '矿池槽位',
    'pool.slotTitle': '矿池槽位 {slot}',
    'pool.url': '矿池地址',
    'pool.workerCode': '矿工号',
    'pool.password': '密码',
    'pool.applying': '应用中...',
    'pool.applySingle': '应用到当前矿机',
    'pool.applyMulti': '应用到所选矿机',
    'pool.fillOneSlot': '请至少先填写一个矿池槽位。',
    'pool.confirmSwitch': '确认切换矿池',
    'pool.confirmSwitchSingle': '将当前矿池配置应用到 {ip}？',
    'pool.confirmSwitchMulti': '将当前矿池配置应用到 {count} 台所选矿机？',
    'view.ipBlock': 'IP 段：{scope}',
    'view.range': '范围：{start} - {end}',
    'view.deleteTitle': '删除视图',
    'view.deleteMessage': '确认删除视图 {scope}？',
    'controller.scanView.loadFailed': '读取视图失败：{error}',
    'controller.scanView.duplicate': '视图已存在，无需重复添加',
    'controller.scan.selectOne': '请至少选择一个扫描视图。',
    'controller.scan.knownEmpty': '所选 IP 段还没有已知矿机记录。',
    'controller.scan.invalidRange': '所选视图没有有效的 IP 范围。',
    'controller.scan.poolCheckFailed': '矿池检查失败：{error}',
    'controller.scan.scanFailed': '扫描失败：{error}',
  };

  static String value(
    AppLanguage language,
    String key, {
    Map<String, String> params = const {},
  }) {
    final table = language == AppLanguage.zh ? _zh : _en;
    final fallback = _en[key] ?? key;
    final template = table[key] ?? fallback;
    return _replaceParams(template, params);
  }

  static String english(String key, {Map<String, String> params = const {}}) {
    final template = _en[key] ?? key;
    return _replaceParams(template, params);
  }

  static String _replaceParams(String template, Map<String, String> params) {
    var output = template;
    for (final entry in params.entries) {
      output = output.replaceAll('{${entry.key}}', entry.value);
    }
    return output;
  }
}
