const Map<String, String> appStringsEn = {
  'app.title.dashboard': 'VolcMiner Dashboard',
  'app.title.scan': 'Scan',
  'app.title.results': 'Scan Results',
  'app.title.settings': 'Settings',
  'app.scan.progress': 'Scanning {current}/{total}',
  'app.scan.paused': 'Scan paused at {current}/{total}',
  'app.scan.finalizing': 'Finalizing scan results...',
  'app.scan.finalizing.logs': 'Analyzing zero-hash miner logs...',
  'app.scan.finalizing.clearRefine':
      'Clearing refine on unresponsive miners...',
  'app.scan.finalizing.recheck': 'Rechecking miners waiting for recovery...',
  'app.scan.finalizing.persist': 'Saving scan results...',
  'app.scanner.open': 'Open Scanner',
  'app.autoScanLog.open': 'Auto Scan Log',
  'app.knownMiners.open': 'Known Miners',
  'app.knownMiners.title': 'Known Miners',
  'app.knownMiners.empty': 'No known miner IPs yet.',
  'app.knownMiners.searchHint': 'Search IP',
  'app.knownMiners.add': 'Add Known IP',
  'app.knownMiners.addTitle': 'Add Known Miner IP',
  'app.knownMiners.addHint': 'Example: 172.100.1.4',
  'app.knownMiners.addSuccess': 'Known miner added: {ip}',
  'app.knownMiners.addDuplicate': 'This IP is already in known miners.',
  'app.knownMiners.addInvalid': 'Invalid IPv4 address.',
  'app.autoScanLog.title': 'Auto Scan Log',
  'app.autoScanLog.empty': 'No auto scan logs yet.',
  'app.autoScanLog.startedAt': 'Start: {time}',
  'app.autoScanLog.finishedAt': 'End: {time}',
  'app.autoScanLog.onlineCount': 'Online miners: {count}',
  'app.autoScanLog.stageDurations': 'Stage durations',
  'app.autoScanLog.status.success': 'Completed',
  'app.autoScanLog.status.failed': 'Failed',
  'app.autoScanLog.status.skipped': 'Skipped',
  'app.autoScanLog.status.running': 'Running',
  'app.autoScanLog.status.unknown': 'Unknown',
  'app.nav.dashboard': 'Dashboard',
  'app.nav.scan': 'Scan',
  'app.nav.results': 'Results',
  'app.nav.settings': 'Settings',
  'overview.onlineMiners': 'Online Miners',
  'overview.unresponsiveMiners': 'Unresponsive Miners',
  'overview.offlineMiners': 'Offline Miners',
  'overview.retiredMiners': 'Pending Retire',
  'overview.abnormalMiners': 'Abnormal Miners',
  'overview.allOnlineTitle': 'All Online Miners',
  'overview.allUnresponsiveTitle': 'All Unresponsive Miners',
  'overview.allOfflineTitle': 'All Offline Miners',
  'overview.allRetiredTitle': 'All Pending Retire',
  'overview.allAbnormalTitle': 'All Abnormal Miners',
  'overview.allFaultTitle': 'All Fault Miners',
  'overview.allSelfCheckFailureTitle': 'All Self-check Failure Miners',
  'abnormal.group.title': 'Abnormal Groups',
  'abnormal.group.soft': 'Soft Abnormal',
  'abnormal.group.softHint':
      'Usually recovering, reboot-check, or temporary high-temperature issues that can still be observed.',
  'abnormal.group.unknown': 'Unknown Abnormal',
  'abnormal.group.unknownHint':
      'The log already shows an issue, but it cannot be categorized clearly yet.',
  'abnormal.group.hard': 'Hard Abnormal',
  'abnormal.group.hardHint':
      'Usually power, fan, or hash board failures that need repair or replacement.',
  'abnormal.type.zero_hash': 'Zero Hash',
  'abnormal.type.reauth': 'Re-authentication',
  'abnormal.type.temperature': 'Temperature',
  'abnormal.type.dropped_board': 'Dropped Board',
  'abnormal.type.all_board_failure': 'All Boards Failed',
  'abnormal.type.power': 'Power',
  'abnormal.type.fan': 'Fan',
  'abnormal.type.hashboard': 'Hash Board',
  'abnormal.type.generic': 'Generic',
  'overview.emptyCategory': 'No miners in this category.',
  'overview.scope': 'IP Block: {scope}',
  'overview.totalHashrate': 'Total Hashrate',
  'overview.onlineRate': 'Online Rate',
  'overview.scanSchedule': 'Scan Schedule',
  'overview.dataAsOf': 'Current data as of {time}',
  'overview.nextScanAt': 'Next scan: {time}',
  'overview.nextScanIn': 'Next scan in {duration}',
  'overview.dataAsOfCompact': 'Updated: {time}',
  'overview.nextScanAtCompact': 'Next scan: {time}',
  'overview.nextScanInCompact': 'Countdown: {duration}',
  'overview.autoScanRunning': 'Auto scan running',
  'overview.autoScanIdle': 'Auto scan idle',
  'overview.autoScanProgress': '{current}/{total}',
  'overview.autoScanFinalizing': 'Organizing scan results...',
  'overview.categoryRefreshTitle': 'Refresh miners',
  'overview.categoryRefreshBody': 'Refresh all {count} miners in this page?',
  'overview.categoryRefreshBusyForeground':
      'A foreground scan is already running.',
  'overview.categoryRefreshBusyBackground':
      'Auto scan is running in the background.',
  'overview.categoryRefreshEmpty':
      'There are no miners to refresh on this page.',
  'overview.categoryRefreshDone': 'Refreshed {count} miners.',
  'overview.autoRefreshOff': 'Auto refresh is off',
  'overview.waitingFirstAutoScan': 'Waiting for the first auto refresh',
  'overview.scanOverdue': 'Scheduled scan is overdue',
  'overview.currentHashrate': 'Current Hashrate',
  'overview.averageHashrate': 'Average Hashrate',
  'overview.averageWindow1h': '1H',
  'overview.averageWindow12h': '12H',
  'overview.hourlyHashrateChart': 'Hourly Average Hashrate',
  'overview.hashrateTrendChart': 'Hashrate Trend',
  'issue.reason.POWER_SUPPLY_FAULT':
      'The power supply is damaged and output voltage is far below the target range.',
  'issue.solution.POWER_SUPPLY_FAULT':
      'Replace the power supply and inspect the output cables and input power before powering on again.',
  'issue.reason.FAN_ERROR': 'A fan failure or abnormal fan speed was detected.',
  'issue.solution.FAN_ERROR':
      'Check fan wiring, fan power, and fan connectors. Replace the failed fan and confirm all fans return to normal speed.',
  'issue.reason.CHAIN_BREAK':
      'A hash board chain communication or ASIC detection error was detected.',
  'issue.solution.CHAIN_BREAK':
      'Inspect the affected hash board, ribbon cable, and connector. If fan errors happened first, repair cooling before replacing the hash board.',
  'issue.reason.OVER_MAX_TEMP':
      'Miner temperature exceeded the safe threshold.',
  'issue.solution.OVER_MAX_TEMP':
      'Improve airflow, clean dust, and verify the fan speed and ambient temperature.',
  'issue.reason.AUTHEN_START_WAIT':
      'The miner restarted authentication after an error and needs a short recovery window.',
  'issue.solution.AUTHEN_START_WAIT':
      'Keep the miner under observation until the next auto scan, then confirm whether the hashrate has recovered.',
  'issue.reason.ERRORMSG':
      'Miner reported an unspecified kernel or hardware error.',
  'issue.solution.ERRORMSG':
      'Open the miner detail page and inspect the full kernel log. Check power, fan speed, and hash board status.',
  'issue.reason.UNKNOWN_ZERO_HASH': 'Unknown zero-hash issue',
  'issue.solution.UNKNOWN_ZERO_HASH':
      'Inspect the miner log, fan speed, temperature, and pool status.',
  'overview.chartEmpty': 'Not enough scan history yet.',
  'overview.chartAxisTime': 'Time',
  'overview.chartAxisHashrate': 'Hashrate (TH/s)',
  'overview.unstableScopes': 'IP Blocks With Repeated Dropouts',
  'overview.unstableScopesEmpty': 'No repeated dropout IP blocks found yet.',
  'app.scan.action.scan': 'Scan',
  'app.scan.action.scanning': 'Scanning...',
  'app.scan.action.pause': 'Pause',
  'app.scan.action.resume': 'Resume',
  'app.scan.action.cancel': 'Cancel Scan',
  'app.scan.action.cancelling': 'Cancelling...',
  'common.clearInput': 'Clear input',
  'settings.language': 'Language',
  'settings.language.en': 'English',
  'settings.language.zh': 'Chinese',
  'settings.fontScale': 'Font Scale',
  'settings.subAccountCard': 'Sub-accounts & Mining URLs',
  'settings.subAccountCardHint':
      'Manage selectable sub-accounts and mining URLs for batch pool configuration.',
  'settings.personalizationCard': 'Personalization',
  'settings.personalizationCardHint':
      'Adjust the default expansion behavior on miner detail pages.',
  'settings.personalizationTitle': 'Personalization',
  'settings.detailChainsCollapsedDefault': 'Collapse board status by default',
  'settings.detailChainsCollapsedHint':
      'When enabled, board status starts collapsed on miner detail pages; otherwise it starts expanded.',
  'settings.detailLogsCollapsedDefault': 'Collapse logs by default',
  'settings.detailLogsCollapsedHint':
      'When enabled, logs start collapsed on miner detail pages; otherwise they start expanded and re-diagnose automatically.',
  'settings.subAccountTitle': 'Sub-accounts',
  'settings.subAccountSection': 'Sub-account list',
  'settings.miningUrlSection': 'Mining URL list',
  'settings.addEntry': 'Add',
  'settings.addEntryTitle': 'Add entry',
  'settings.addEntryType': 'Type',
  'settings.addEntryType.subAccount': 'Sub-account',
  'settings.addEntryType.miningUrl': 'Mining URL',
  'settings.addEntryValue': 'Value',
  'settings.addEntryValueHint.subAccount': 'Example: hashunionltc.ak',
  'settings.addEntryValueHint.miningUrl':
      'Example: stratum+tcp://ltc.po.hash7.info:2002',
  'settings.emptySubAccounts': 'No sub-accounts yet.',
  'settings.emptyMiningUrls': 'No mining URLs yet.',
  'settings.deleteSubAccountTitle': 'Delete sub-account',
  'settings.deleteSubAccountBody': 'Delete sub-account {value}?',
  'settings.deleteMiningUrlTitle': 'Delete mining URL',
  'settings.deleteMiningUrlBody': 'Delete mining URL {value}?',
  'settings.choose': 'Choose',
  'settings.autoScanWindow': 'Auto Scan Window',
  'settings.autoScanStart': 'Start Time',
  'settings.autoScanStop': 'Stop Time',
  'settings.autoRefresh': 'Auto Refresh',
  'settings.showOffline': 'Show Offline Miners',
  'settings.collectLogs': 'Collect Logs',
  'settings.refreshInterval': 'Auto refresh interval (sec)',
  'settings.scanConcurrency': 'Scan Concurrency',
  'settings.scanConcurrencyWarningTitle': 'Use concurrency {value}?',
  'settings.scanConcurrencyWarningBody':
      'Concurrency {value} can significantly increase pressure on this device, Wi-Fi, router, and miner web service.',
  'settings.scanConcurrencyWarningHint':
      'Use it only when the local network is stable and device performance is strong.',
  'dashboard.scanType': 'Scan Type',
  'dashboard.scanType.full': 'Full Scan',
  'dashboard.scanType.known': 'Known Scan',
  'dashboard.scanType.fullDesc':
      'Scan the full selected IP range, for example 1-255.',
  'dashboard.scanType.knownDesc':
      'Only scan known miner IPs already recorded for this IP block.',
  'dashboard.minerAuth': 'Miner Auth',
  'dashboard.addScanView': 'Add Scan View',
  'dashboard.searchIpBlock': 'Search IP Block',
  'dashboard.searchIpBlockHint': 'Example: 100.16',
  'dashboard.loadingCloudViews': 'Loading cloud views...',
  'dashboard.syncingCloudViews': 'Syncing cloud views in the background...',
  'dashboard.minerUsername': 'Miner Username',
  'dashboard.minerPassword': 'Miner Password',
  'dashboard.baseIpBlock': 'Base IP Block',
  'dashboard.ipBlockOptional': 'IP Block (optional)',
  'dashboard.baseIpBlockHint': 'Example: 172.100',
  'dashboard.ipBlockHint': 'Example: 172.100.1',
  'dashboard.batchAdd': 'Batch Add Views',
  'dashboard.batchAddTitle': 'Batch add views',
  'dashboard.batchAddSubtitle':
      'Add IP blocks in order, for example 172.100.1 to 172.100.20.',
  'dashboard.batchStart': 'Batch Start',
  'dashboard.batchEnd': 'Batch End',
  'dashboard.startIp': 'Start IP / Host (optional)',
  'dashboard.endIp': 'End IP / Host (optional)',
  'dashboard.startIpHint': '1 or 172.100.1.1',
  'dashboard.endIpHint': '255 or 172.100.1.255',
  'dashboard.addView': 'Add View',
  'dashboard.selectionMode': 'Selection Mode:',
  'dashboard.selectionMode.single': 'Single',
  'dashboard.selectionMode.multi': 'Multi',
  'dashboard.selectionMode.selectAll': 'Select All',
  'dashboard.error.invalidIpBlock': 'Invalid IP Block format',
  'dashboard.error.invalidRange':
      'Invalid start/end IP format. You can use a full IP or a host suffix with IP Block.',
  'dashboard.error.startGreaterThanEnd':
      'Start IP must be less than or equal to End IP.',
  'dashboard.error.batchBase':
      'Batch add requires a base IP Block like 172.100',
  'dashboard.error.batchBaseInvalid': 'Invalid base IP Block',
  'dashboard.error.batchRangeInvalid': 'Invalid batch range',
  'dashboard.defaultViewName': 'IP Block',
  'results.empty': 'No scan records yet. Start a scan from Dashboard first.',
  'results.searchLabel': 'Search IP Block',
  'results.searchHint': 'Example: 100.1 or 101.16',
  'results.lastScan': 'Last Scan: {time}',
  'results.ipBlock': 'IP Block: {scope}',
  'results.onlineMiners': 'Online: {count}',
  'results.unresponsiveMiners': 'Unresponsive: {count}',
  'results.offlineMiners': 'Offline: {count}',
  'results.retiredMiners': 'Pending Retire: {count}',
  'results.trackedMiners': 'Tracked Miners: {count}',
  'results.issueCount': 'Issues: {count}',
  'segment.title': '{scope} Details',
  'segment.lastScan': 'Last Scan: {time}',
  'segment.onlineCount': 'Online Count: {count}',
  'segment.filter.all': 'All',
  'segment.filter.online': 'Online',
  'segment.filter.unresponsive': 'Unresponsive',
  'segment.filter.abnormal': 'Abnormal',
  'segment.filter.offline': 'Offline',
  'segment.filter.retired': 'Pending Retire',
  'segment.selected': 'Selected: {count}',
  'segment.selectAll': 'Select All',
  'segment.cancelSelect': 'Cancel Selection',
  'segment.batchLedOn': 'Batch LED On',
  'segment.batchLedOnBusy': 'Turning on...',
  'segment.batchLedOff': 'Batch LED Off',
  'segment.batchLedOffBusy': 'Turning off...',
  'segment.poolConfig': 'Pool Config ({count})',
  'segment.batchClear': 'Batch Clear Refine',
  'segment.batchClearBusy': 'Clearing...',
  'segment.batchReboot': 'Batch Reboot Miners',
  'segment.batchRebootBusy': 'Rebooting...',
  'segment.longPressHint':
      'Long press a miner record to enter multi-select mode.',
  'segment.ledOnTag': 'LED on',
  'segment.issueReason': 'Issue: {reason}',
  'segment.issueSolution': 'Suggestion: {solution}',
  'segment.issueSecondary': 'Secondary symptom: {reason}',
  'segment.deleteMiner': 'Delete Miner',
  'segment.deleteMinerMessage': 'Delete off-shelf miner record {ip}?',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.confirm': 'Confirm',
  'segment.confirmLedOnTitle': 'Confirm batch LED on',
  'segment.confirmLedOnMessage':
      'Turn on the indicator light for {count} selected miners?',
  'segment.confirmLedOffTitle': 'Confirm batch LED off',
  'segment.confirmLedOffMessage':
      'Turn off the indicator light for {count} selected miners?',
  'segment.confirmClearTitle': 'Confirm batch clear refine',
  'segment.confirmClearMessage': 'Clear refine for {count} selected miners?',
  'segment.confirmRebootTitle': 'Confirm batch reboot',
  'segment.confirmRebootMessage': 'Reboot {count} selected miners?',
  'miner.status': 'Status: {status}',
  'miner.hashrate5s': 'Hashrate 5s: {value}',
  'miner.hashrateAvg': 'Hashrate avg: {value}',
  'miner.ambientTemp': 'Ambient temp: {value}',
  'miner.power': 'Power: {value}',
  'miner.fans': 'Fans: {value}',
  'miner.runningMode': 'Running mode: {value}',
  'miner.updated': 'Updated: {time}',
  'miner.indicatorSwitch': 'Indicator switch',
  'miner.sendingCommand': 'Sending command...',
  'miner.indicatorHint': 'Uses diagnostics backend to control the miner LED.',
  'miner.clearRefine': 'Clear Refine',
  'miner.clearRefineMessage': 'Clear refine for {ip}?',
  'miner.rebootMiner': 'Reboot Miner',
  'miner.rebootMinerMessage': 'Reboot {ip} now?',
  'miner.refresh': 'Refresh',
  'miner.retire': 'Retire',
  'miner.retireMessage': 'Retire {ip} and remove it from known miner records?',
  'miner.refreshing': 'Refreshing miner...',
  'miner.refreshDone': 'Miner refreshed: {ip}',
  'miner.refreshFailed': 'Miner refresh failed: {error}',
  'miner.poolConfig': 'Pool Config',
  'miner.kernelLog': 'Kernel Log',
  'miner.kernelLogLoading': 'Loading full kernel log...',
  'miner.kernelLogFailed': 'Load failed',
  'miner.kernelLogCollapsed': 'Expand to load the full kernel log.',
  'miner.kernelLogReady': 'Full log loaded. Drag the scrollbars to view it.',
  'miner.kernelLogPlaceholder': 'Expand to load the full work log.',
  'miner.kernelLogError': 'Kernel log load failed: {error}',
  'miner.issueCardTitle': 'Zero Hash Diagnosis',
  'miner.issueReason': 'Reason: {reason}',
  'miner.issueSolution': 'Suggestion: {solution}',
  'miner.issueCode': 'Code: {code}',
  'miner.issueSecondary': 'Secondary symptom: {reason}',
  'status.online': 'Online',
  'status.offline': 'Offline',
  'pool.applyTitle': 'Apply Pool Config',
  'pool.title': 'Pool Config',
  'pool.targetSingle': 'Target: {ip}',
  'pool.targetMulti': 'Targets: {count} miners',
  'pool.singleHint':
      'The pool fields below are loaded from the current miner first.',
  'pool.multiHint':
      'Edit the pool slots below, then apply them to the selected miners.',
  'pool.runningModeTitle': 'Running Mode',
  'pool.runningModeSubtitle':
      'Running mode is part of the same configuration and will be saved together.',
  'pool.slots': 'Pool Slots',
  'pool.slotTitle': 'Pool Slot {slot}',
  'pool.url': 'Pool URL',
  'pool.workerCode': 'Worker Code',
  'pool.password': 'Password',
  'pool.mode.normal': 'Normal Mode',
  'pool.mode.overclock': 'Overclock Mode',
  'pool.mode.custom': 'Custom Voltage/Frequency',
  'pool.mode.debug': 'Debug Mode',
  'pool.mode.lowPower': 'Low Power Mode',
  'pool.mode.superLowPower': 'Super Low Power Mode',
  'pool.mode.sleep': 'Sleep Mode',
  'pool.applying': 'Applying...',
  'pool.applySingle': 'Apply to Miner',
  'pool.applyMulti': 'Apply to Selected Miners',
  'pool.fillOneSlot': 'Please fill at least one pool slot first.',
  'pool.confirmSwitch': 'Confirm Pool Switch',
  'pool.confirmSwitchSingle': 'Apply the current pool configuration to {ip}?',
  'pool.confirmSwitchMulti':
      'Apply the current pool configuration to {count} selected miners?',
  'pool.multiTitle': 'Batch Pool Config',
  'pool.multiHintDetailed':
      'Choose a sub-account and mining URL for each slot. Worker names will be generated as sub-account.IP.',
  'pool.selectSubAccount': 'Select sub-account',
  'pool.selectMiningUrl': 'Select mining URL',
  'pool.workerPreview': 'Worker preview',
  'pool.workerPreviewHint': 'Will use {worker}',
  'pool.multiApply': 'Apply to selected miners',
  'pool.needSubAccount':
      'Please add at least one sub-account in Settings first.',
  'pool.needMiningUrl': 'Please add at least one mining URL in Settings first.',
  'pool.subAccount': 'Sub-account',
  'pool.miningUrl': 'Mining URL',
  'view.ipBlock': 'IP Block: {scope}',
  'view.range': 'Range: {start} - {end}',
  'view.deleteTitle': 'Delete View',
  'view.deleteMessage': 'Delete view {scope}?',
  'controller.scanView.loadFailed': 'Failed to load scan views: {error}',
  'controller.scanView.duplicate': 'This view already exists.',
  'controller.scan.selectOne': 'Please select at least one scan view.',
  'controller.scan.knownEmpty':
      'Selected IP blocks do not have known miners yet.',
  'controller.scan.invalidRange':
      'Selected views do not contain valid IP ranges.',
  'controller.scan.poolCheckFailed': 'Pool check failed: {error}',
  'controller.scan.scanFailed': 'Scan failed: {error}',
};
