const Map<String, String> appStringsZh = {
  'app.title.dashboard': '火山矿机面板',
  'app.title.scan': '扫描',
  'app.title.results': '扫描结果',
  'app.title.settings': '设置',
  'app.scan.progress': '扫描中 {current}/{total}',
  'app.scan.paused': '扫描已暂停 {current}/{total}',
  'app.scan.finalizing': '正在整理扫描结果...',
  'app.scan.finalizing.logs': '正在分析零算力矿机日志...',
  'app.scan.finalizing.clearRefine': '正在清除未响应矿机自适应...',
  'app.scan.finalizing.recheck': '正在复查等待恢复的矿机...',
  'app.scan.finalizing.persist': '正在保存扫描结果...',
  'app.scanner.open': '打开扫码',
  'app.autoScanLog.open': '自动扫描日志',
  'app.knownMiners.open': '已知矿机',
  'app.knownMiners.title': '已知矿机',
  'app.knownMiners.empty': '暂无已知矿机 IP。',
  'app.knownMiners.searchHint': '搜索 IP',
  'app.knownMiners.add': '添加已知 IP',
  'app.knownMiners.addTitle': '添加已知矿机 IP',
  'app.knownMiners.addHint': '例如：172.100.1.4',
  'app.knownMiners.addSuccess': '已添加已知矿机：{ip}',
  'app.knownMiners.addDuplicate': '该 IP 已存在于已知矿机中。',
  'app.knownMiners.addInvalid': 'IP 地址格式无效。',
  'app.autoScanLog.title': '自动扫描日志',
  'app.autoScanLog.empty': '暂无自动扫描日志。',
  'app.autoScanLog.startedAt': '开始：{time}',
  'app.autoScanLog.finishedAt': '结束：{time}',
  'app.autoScanLog.onlineCount': '在线矿机：{count}',
  'app.autoScanLog.stageDurations': '阶段耗时',
  'app.autoScanLog.status.success': '已完成',
  'app.autoScanLog.status.failed': '失败',
  'app.autoScanLog.status.skipped': '已跳过',
  'app.autoScanLog.status.running': '进行中',
  'app.autoScanLog.status.unknown': '未知',
  'app.nav.dashboard': '面板',
  'app.nav.scan': '扫描',
  'app.nav.results': '结果',
  'app.nav.settings': '设置',
  'overview.onlineMiners': '在线矿机',
  'overview.unresponsiveMiners': '未响应矿机',
  'overview.offlineMiners': '离线矿机',
  'overview.retiredMiners': '待下架矿机',
  'overview.abnormalMiners': '异常矿机',
  'overview.allOnlineTitle': '全部在线矿机',
  'overview.allUnresponsiveTitle': '全部未响应矿机',
  'overview.allOfflineTitle': '全部离线矿机',
  'overview.allRetiredTitle': '全部待下架矿机',
  'overview.allAbnormalTitle': '全部异常矿机',
  'overview.allFaultTitle': '全部故障矿机',
  'overview.allSelfCheckFailureTitle': '全部自检失败矿机',
  'abnormal.group.title': '异常分组',
  'abnormal.group.soft': '软异常',
  'abnormal.group.softHint': '常见为等待恢复、重启复查、临时高温等可继续观察的问题。',
  'abnormal.group.unknown': '未分类异常',
  'abnormal.group.unknownHint': '日志里已有异常，但暂时无法明确归类，建议继续查看详情。',
  'abnormal.group.hard': '硬异常',
  'abnormal.group.hardHint': '常见为电源、风扇、算力板等需要处理或更换的故障。',
  'abnormal.type.zero_hash': '零算力异常',
  'abnormal.type.reauth': '重新认证',
  'abnormal.type.temperature': '温度异常',
  'abnormal.type.dropped_board': '掉板异常',
  'abnormal.type.all_board_failure': '全板异常',
  'abnormal.type.power': '电源异常',
  'abnormal.type.fan': '风扇异常',
  'abnormal.type.hashboard': '算力板异常',
  'abnormal.type.generic': '通用异常',
  'overview.emptyCategory': '当前分类下没有矿机。',
  'overview.scope': 'IP 段：{scope}',
  'overview.totalHashrate': '整体算力',
  'overview.onlineRate': '在线率',
  'overview.scanSchedule': '扫描计划',
  'overview.dataAsOf': '当前信息截至 {time}',
  'overview.nextScanAt': '下次扫描时间：{time}',
  'overview.nextScanIn': '距离下次扫描还有 {duration}',
  'overview.dataAsOfCompact': '更新时间：{time}',
  'overview.nextScanAtCompact': '下次扫描：{time}',
  'overview.nextScanInCompact': '扫描倒计时：{duration}',
  'overview.autoScanRunning': '自动扫描进行中',
  'overview.autoScanIdle': '自动扫描空闲',
  'overview.autoScanProgress': '{current}/{total}',
  'overview.autoScanFinalizing': '正在整理扫描结果...',
  'overview.categoryRefreshTitle': '刷新矿机',
  'overview.categoryRefreshBody': '将刷新当前页面中的 {count} 台矿机，是否继续？',
  'overview.categoryRefreshBusyForeground': '当前已有前台扫描正在进行。',
  'overview.categoryRefreshBusyBackground': '后台自动扫描正在运行。',
  'overview.categoryRefreshEmpty': '当前页面没有可刷新的矿机。',
  'overview.categoryRefreshDone': '已刷新 {count} 台矿机。',
  'overview.autoRefreshOff': '自动刷新未开启',
  'overview.waitingFirstAutoScan': '等待首次自动刷新',
  'overview.scanOverdue': '已到计划时间，等待执行',
  'overview.currentHashrate': '当前整体算力',
  'overview.averageHashrate': '平均算力',
  'overview.averageWindow1h': '1H',
  'overview.averageWindow12h': '12H',
  'overview.hourlyHashrateChart': '小时平均算力折线图',
  'overview.hashrateTrendChart': '整体算力变化',
  'issue.reason.POWER_SUPPLY_FAULT': '电源已损坏，输出电压明显低于目标范围。',
  'issue.solution.POWER_SUPPLY_FAULT': '建议直接更换电源，并在重新上电前检查输出线缆和输入供电是否正常。',
  'issue.reason.FAN_ERROR': '检测到风扇故障或风扇转速异常。',
  'issue.solution.FAN_ERROR': '请检查风扇供电、接线和插头，必要时更换故障风扇，并确认所有风扇恢复正常转速。',
  'issue.reason.CHAIN_BREAK': '检测到算力板链路通信异常或 ASIC 识别异常。',
  'issue.solution.CHAIN_BREAK':
      '请检查异常算力板、排线和连接器。如果更早日志里先出现风扇异常，应优先修复散热问题，再处理算力板。',
  'issue.reason.OVER_MAX_TEMP': '矿机温度超过安全阈值。',
  'issue.solution.OVER_MAX_TEMP': '请改善风道、清理灰尘，并检查风扇转速和环境温度。',
  'issue.reason.AUTHEN_START_WAIT': '矿机报错后重新开始认证，需要等待恢复。',
  'issue.solution.AUTHEN_START_WAIT': '请继续观察，等待下一次自动扫描后再确认算力是否恢复正常。',
  'issue.reason.ERRORMSG': '矿机上报了未细分的内核或硬件错误。',
  'issue.solution.ERRORMSG': '请打开矿机详情页查看完整内核日志，并重点检查电源、风扇和算力板状态。',
  'issue.reason.UNKNOWN_ZERO_HASH': '零算力原因未识别。',
  'issue.solution.UNKNOWN_ZERO_HASH': '请检查矿机日志、风扇转速、温度以及矿池连接状态。',
  'issue.reason.ZERO_HASH_RESTARTING': '当前矿机出现零算力，正在重启自检，等待下一轮扫描确认是否恢复。',
  'issue.solution.ZERO_HASH_RESTARTING': '请继续观察矿机日志和算力变化，重点确认风扇、温度和矿池连接是否正常。',
  'issue.reason.ZERO_HASH_RESTART_FAILED': '零算力在重启自检后仍未恢复，说明问题还没有被自动修复。',
  'issue.solution.ZERO_HASH_RESTART_FAILED': '请检查电源、算力板和日志，必要时进一步查看完整内核日志。',
  'issue.reason.HASHBOARD_DROPPED_RESTARTING': '检测到掉板，矿机正在重启以确认算力板是否能够恢复。',
  'issue.solution.HASHBOARD_DROPPED_RESTARTING':
      '等待下一轮扫描确认掉板是否恢复，并检查相关排线和供电连接。',
  'issue.reason.HASHBOARD_DROPPED_RESTART_FAILED':
      '掉板在重启后仍未恢复，通常需要进一步维修或更换相关算力板。',
  'issue.solution.HASHBOARD_DROPPED_RESTART_FAILED':
      '请检查掉板对应的排线、连接器和供电，必要时更换故障算力板。',
  'issue.reason.HASHBOARD_ALL_FAILED_RESTARTING': '所有算力板都报错，矿机正在重启确认是否能恢复。',
  'issue.solution.HASHBOARD_ALL_FAILED_RESTARTING':
      '等待下一轮扫描确认是否恢复，同时检查电源、排线和控制板连接。',
  'issue.reason.HASHBOARD_ALL_FAILED_NEEDS_REPLACEMENT':
      '所有算力板重启后仍然报错，通常已经需要更换相关硬件。',
  'issue.solution.HASHBOARD_ALL_FAILED_NEEDS_REPLACEMENT':
      '请检查全部算力板、供电和控制板连接，通常需要进一步维修或更换。',
  'issue.reason.TEMP_FULL_SPEED_RECOVERING': '矿机因高温触发了全速保护，当前正在观察是否恢复。',
  'issue.solution.TEMP_FULL_SPEED_RECOVERING': '请先改善散热和风道，下一轮扫描确认温度和算力是否回落。',
  'issue.reason.TEMP_FULL_SPEED_PERSISTED': '矿机高温保护已经持续了多次扫描，算力还没有恢复。',
  'issue.solution.TEMP_FULL_SPEED_PERSISTED': '请重点检查环境温度、风扇转速和散热条件，先处理温控问题。',
  'issue.reason.SERVER_ALERT': '服务器侧告警，需要进一步查看后端状态。',
  'issue.solution.SERVER_ALERT': '请查看服务器日志或告警详情，确认是否需要手动处理。',
  'overview.chartEmpty': '当前历史扫描数据不足。',
  'overview.chartAxisTime': '时间',
  'overview.chartAxisHashrate': '算力 (TH/s)',
  'overview.unstableScopes': '存在多次掉线问题的 IP 段',
  'overview.unstableScopesEmpty': '暂时没有发现多次掉线的 IP 段。',
  'app.scan.action.scan': '开始扫描',
  'app.scan.action.scanning': '扫描中...',
  'app.scan.action.pause': '暂停',
  'app.scan.action.resume': '继续扫描',
  'app.scan.action.cancel': '取消扫描',
  'app.scan.action.cancelling': '正在取消...',
  'common.clearInput': '清空输入',
  'settings.language': '语言',
  'settings.language.en': 'English',
  'settings.language.zh': '中文',
  'settings.fontScale': '字体大小',
  'settings.subAccountCard': '子账号与挖掘地址',
  'settings.subAccountCardHint': '管理批量矿池配置时可选的子账号和挖掘 URL。',
  'settings.personalizationCard': '个性化设置',
  'settings.personalizationCardHint': '调整矿机详情页的默认展开方式。',
  'settings.personalizationTitle': '个性化设置',
  'settings.detailChainsCollapsedDefault': '默认运算板状态折叠',
  'settings.detailChainsCollapsedHint': '开启后，进入矿机详情页时运算板状态默认折叠；关闭则默认展开。',
  'settings.detailLogsCollapsedDefault': '默认日志折叠',
  'settings.detailLogsCollapsedHint': '开启后，进入矿机详情页时日志默认折叠；关闭则默认展开，并会自动更新诊断。',
  'settings.subAccountTitle': '子账号',
  'settings.subAccountSection': '子账号列表',
  'settings.miningUrlSection': '挖掘 URL 列表',
  'settings.addEntry': '添加',
  'settings.addEntryTitle': '新增配置项',
  'settings.addEntryType': '类型',
  'settings.addEntryType.subAccount': '子账号',
  'settings.addEntryType.miningUrl': '挖掘 URL',
  'settings.addEntryValue': '内容',
  'settings.addEntryValueHint.subAccount': '例如 hashunionltc.ak',
  'settings.addEntryValueHint.miningUrl':
      '例如 stratum+tcp://ltc.po.hash7.info:2002',
  'settings.emptySubAccounts': '还没有子账号。',
  'settings.emptyMiningUrls': '还没有挖掘 URL。',
  'settings.deleteSubAccountTitle': '删除子账号',
  'settings.deleteSubAccountBody': '确认删除子账号 {value}？',
  'settings.deleteMiningUrlTitle': '删除挖掘 URL',
  'settings.deleteMiningUrlBody': '确认删除挖掘 URL {value}？',
  'settings.choose': '选择',
  'settings.autoScanWindow': '自动扫描时间窗',
  'settings.autoScanStart': '启用时间',
  'settings.autoScanStop': '停止时间',
  'settings.autoRefresh': '自动刷新',
  'settings.showOffline': '显示离线矿机',
  'settings.collectLogs': '采集日志',
  'settings.refreshInterval': '自动刷新间隔（秒）',
  'settings.scanConcurrency': '扫描并发数',
  'settings.scanConcurrencyWarningTitle': '确认使用并发 {value}',
  'settings.scanConcurrencyWarningBody':
      '并发 {value} 会明显增加本机、Wi‑Fi、路由器和矿机 Web 服务的负载。',
  'settings.scanConcurrencyWarningHint': '仅建议在局域网稳定且设备性能足够时使用。',
  'dashboard.scanType': '扫描方式',
  'dashboard.scanType.full': '全段扫描',
  'dashboard.scanType.known': '已知扫描',
  'dashboard.scanType.fullDesc': '扫描所选 IP 范围内的完整地址，例如 1-255。',
  'dashboard.scanType.knownDesc': '只扫描结果页中当前 IP 段已经记录过的矿机 IP。',
  'dashboard.minerAuth': '矿机认证',
  'dashboard.addScanView': '添加视图',
  'dashboard.searchIpBlock': '搜索 IP 段',
  'dashboard.searchIpBlockHint': '例如 100.16',
  'dashboard.loadingCloudViews': '正在加载云端视图...',
  'dashboard.syncingCloudViews': '正在后台同步云端视图...',
  'dashboard.minerUsername': '矿机用户名',
  'dashboard.minerPassword': '矿机密码',
  'dashboard.baseIpBlock': '基础 IP 段',
  'dashboard.ipBlockOptional': 'IP 段（可选）',
  'dashboard.baseIpBlockHint': '例如 172.100',
  'dashboard.ipBlockHint': '例如 172.100.1',
  'dashboard.batchAdd': '批量添加视图',
  'dashboard.batchAddTitle': '批量添加视图',
  'dashboard.batchAddSubtitle': '按范围逐个添加 IP 段，例如 172.100.1 到 172.100.20。',
  'dashboard.batchStart': '批量起始',
  'dashboard.batchEnd': '批量结束',
  'dashboard.startIp': '起始 IP / Host（可选）',
  'dashboard.endIp': '结束 IP / Host（可选）',
  'dashboard.startIpHint': '1 或 172.100.1.1',
  'dashboard.endIpHint': '255 或 172.100.1.255',
  'dashboard.addView': '添加视图',
  'dashboard.selectionMode': '选择模式：',
  'dashboard.selectionMode.single': '单选',
  'dashboard.selectionMode.multi': '多选',
  'dashboard.selectionMode.selectAll': '全选',
  'dashboard.error.invalidIpBlock': 'IP 段格式不正确',
  'dashboard.error.invalidRange': '起始或结束 IP 格式不正确。可以输入完整 IP，或在 IP 段后只输入主机尾段。',
  'dashboard.error.startGreaterThanEnd': '起始 IP 不能大于结束 IP。',
  'dashboard.error.batchBase': '批量添加需要输入类似 172.100 的基础 IP 段',
  'dashboard.error.batchBaseInvalid': '基础 IP 段无效',
  'dashboard.error.batchRangeInvalid': '批量范围无效',
  'dashboard.defaultViewName': 'IP 段',
  'results.empty': '还没有扫描记录，请先在 Dashboard 发起扫描。',
  'results.searchLabel': '搜索 IP 段',
  'results.searchHint': '例如 100.1 或 101.16',
  'results.lastScan': '上次扫描：{time}',
  'results.ipBlock': 'IP 段：{scope}',
  'results.onlineMiners': '在线矿机：{count}',
  'results.unresponsiveMiners': '未响应：{count}',
  'results.offlineMiners': '离线：{count}',
  'results.retiredMiners': '待下架：{count}',
  'results.trackedMiners': '记录矿机：{count}',
  'results.issueCount': '异常：{count}',
  'segment.title': '{scope} 搜索详情',
  'segment.lastScan': '上次扫描：{time}',
  'segment.onlineCount': '在线数量：{count}',
  'segment.filter.all': '全部',
  'segment.filter.online': '在线',
  'segment.filter.unresponsive': '未响应',
  'segment.filter.abnormal': '异常',
  'segment.filter.offline': '离线',
  'segment.filter.retired': '待下架',
  'segment.selected': '已选择：{count}',
  'segment.selectAll': '全选',
  'segment.cancelSelect': '取消选择',
  'segment.batchLedOn': '批量开灯',
  'segment.batchLedOnBusy': '开灯中...',
  'segment.batchLedOff': '批量关灯',
  'segment.batchLedOffBusy': '关灯中...',
  'segment.poolConfig': '矿池配置（{count}）',
  'segment.batchClear': '批量清除自适应',
  'segment.batchClearBusy': '清除中...',
  'segment.batchReboot': '批量重启矿机',
  'segment.batchRebootBusy': '重启中...',
  'segment.longPressHint': '长按单个矿机记录可进入批量选择模式。',
  'segment.ledOnTag': '已打开指示灯',
  'segment.issueReason': '原因：{reason}',
  'segment.issueSolution': '建议：{solution}',
  'segment.issueSecondary': '次级症状：{reason}',
  'segment.deleteMiner': '删除矿机',
  'segment.deleteMinerMessage': '删除下架矿机记录 {ip}？',
  'common.cancel': '取消',
  'common.delete': '删除',
  'common.confirm': '确认',
  'segment.confirmLedOnTitle': '确认批量打开指示灯',
  'segment.confirmLedOnMessage': '本次将打开 {count} 台矿机的指示灯，是否继续？',
  'segment.confirmLedOffTitle': '确认批量关闭指示灯',
  'segment.confirmLedOffMessage': '本次将关闭 {count} 台矿机的指示灯，是否继续？',
  'segment.confirmClearTitle': '确认批量清除自适应',
  'segment.confirmClearMessage': '本次将清除 {count} 台矿机的自适应，是否继续？',
  'segment.confirmRebootTitle': '确认批量重启矿机',
  'segment.confirmRebootMessage': '本次将重启 {count} 台矿机，是否继续？',
  'miner.status': '状态：{status}',
  'miner.hashrate5s': '5 秒算力：{value}',
  'miner.hashrateAvg': '平均算力：{value}',
  'miner.ambientTemp': '环境温度：{value}',
  'miner.power': '功耗：{value}',
  'miner.fans': '风扇：{value}',
  'miner.runningMode': '运行模式：{value}',
  'miner.updated': '更新时间：{time}',
  'miner.indicatorSwitch': '指示灯开关',
  'miner.sendingCommand': '正在发送指令...',
  'miner.indicatorHint': '通过诊断后台控制矿机指示灯。',
  'miner.clearRefine': '清除自适应',
  'miner.clearRefineMessage': '确认清除 {ip} 的自适应吗？',
  'miner.rebootMiner': '重启矿机',
  'miner.rebootMinerMessage': '确认现在重启 {ip} 吗？',
  'miner.refresh': '刷新',
  'miner.retire': '下架',
  'miner.retireMessage': '确认将 {ip} 下架并移出已知矿机记录？',
  'miner.refreshing': '正在刷新矿机...',
  'miner.refreshDone': '矿机已刷新：{ip}',
  'miner.refreshFailed': '矿机刷新失败：{error}',
  'miner.poolConfig': '矿池配置',
  'miner.kernelLog': '工作日志',
  'miner.kernelLogLoading': '正在读取完整 kernel log...',
  'miner.kernelLogFailed': '读取失败',
  'miner.kernelLogCollapsed': '展开后单独读取完整日志。',
  'miner.kernelLogReady': '完整日志已加载，可拖动滚动条查看。',
  'miner.kernelLogPlaceholder': '展开后单独查找完整工作日志。',
  'miner.kernelLogError': '工作日志读取失败：{error}',
  'miner.issueCardTitle': '零算力诊断',
  'miner.issueReason': '原因：{reason}',
  'miner.issueSolution': '建议：{solution}',
  'miner.issueCode': '错误码：{code}',
  'miner.issueSecondary': '次级症状：{reason}',
  'status.online': '在线',
  'status.offline': '离线',
  'pool.applyTitle': '应用矿池配置',
  'pool.title': '矿池配置',
  'pool.targetSingle': '目标：{ip}',
  'pool.targetMulti': '目标：{count} 台矿机',
  'pool.singleHint': '下面的矿池输入框会先加载当前矿机的配置。',
  'pool.multiHint': '修改下面的矿池槽位后，再批量下发到所选矿机。',
  'pool.runningModeTitle': '运行模式',
  'pool.runningModeSubtitle': '运行模式和矿池配置属于同一份设置，保存时会一并下发。',
  'pool.slots': '矿池槽位',
  'pool.slotTitle': '矿池槽位 {slot}',
  'pool.url': '矿池地址',
  'pool.workerCode': '矿工号',
  'pool.password': '密码',
  'pool.mode.normal': '正常模式',
  'pool.mode.overclock': '超频模式',
  'pool.mode.custom': '自定义电压/频率',
  'pool.mode.debug': '调试模式',
  'pool.mode.lowPower': '低功耗模式',
  'pool.mode.superLowPower': '超级低功耗模式',
  'pool.mode.sleep': '睡眠模式',
  'pool.applying': '应用中...',
  'pool.applySingle': '应用到当前矿机',
  'pool.applyMulti': '应用到所选矿机',
  'pool.fillOneSlot': '请至少先填写一个矿池槽位。',
  'pool.confirmSwitch': '确认切换矿池',
  'pool.confirmSwitchSingle': '将当前矿池配置应用到 {ip}？',
  'pool.confirmSwitchMulti': '将当前矿池配置应用到 {count} 台所选矿机？',
  'pool.multiTitle': '批量矿池配置',
  'pool.multiHintDetailed': '为三个矿池槽位分别选择子账号和挖掘 URL，矿工名会自动生成为 子账号.IP。',
  'pool.selectSubAccount': '选择子账号',
  'pool.selectMiningUrl': '选择挖掘 URL',
  'pool.workerPreview': '矿工名预览',
  'pool.workerPreviewHint': '将自动使用 {worker}',
  'pool.multiApply': '应用到所选矿机',
  'pool.needSubAccount': '请先在设置页添加至少一个子账号。',
  'pool.needMiningUrl': '请先在设置页添加至少一个挖掘 URL。',
  'pool.subAccount': '子账号',
  'pool.miningUrl': '挖掘 URL',
  'view.ipBlock': 'IP 段：{scope}',
  'view.range': '范围：{start} - {end}',
  'view.deleteTitle': '删除视图',
  'view.deleteMessage': '确认删除视图 {scope}？',
  'controller.scanView.loadFailed': '读取视图失败：{error}',
  'controller.scanView.duplicate': '视图已存在，无需重复添加',
  'controller.scan.selectOne': '请至少选择一个扫描视图。',
  'controller.scan.knownEmpty': '所选 IP 段还没有已知矿机记录。',
  'controller.scan.invalidRange': '所选视图没有有效的 IP 范围。',
  'controller.scan.poolCheckFailed': '矿池检查失败：{error}',
  'controller.scan.scanFailed': '扫描失败：{error}',
};
